### PR TITLE
Updated for Prooph/Common v4

### PR DESCRIPTION
**Pull request by mkherlakian**

### CODE REVIEW

**Comment by mkherlakian** [comment]
Checks fail b/c prooph common v4 supports only php 7.1

**Comment by codeliner** [comment]
thx @mkherlakian 

Can you change [travis config](https://github.com/prooph/psb-bernard-producer/blob/master/.travis.yml#L3) to use that [matrix](https://github.com/prooph/common/blob/master/.travis.yml#L3) instead. This should solve the problem with PHP version.

**Comment by mkherlakian** [comment]
Hey @codeliner I updated the Travis config with your suggested matrix, but also had to add react/promise as a dependency to make tests pass - otherwise one of the tests threw a TypeError as it uses a deferred promise. Should be good to go. 
I had refrained from updating as I wasn't sure that you wanted to drop support for php 5.X, but I guess since prooph/common v4 uses php7 only features, it makes sense. Cheers!

**Review by codeliner — APPROVED** [review]

**Comment by codeliner** [comment]
thx @mkherlakian awesome work!

**Pull request merged**
